version: '3.1'

services:

  app-php-apache:
    build:
      args:
        container_project_path: /var/www/html/
        host_project_path: ./workspace/
        uid: 1000
        user: $USER
      context: .
      dockerfile: ./Dockerfile
    image: app-php-apache
    ports:
      - 80:80
    volumes:
      - ./workspace/:/var/www/html/

  app-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql/

  app-phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: app-mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 3333:80

volumes:
  mysql-data: